language: python
dist: xenial
sudo: required
env:
python:
    - "3.6"
    - "3.7"
    - "3.7-dev"
install:
    - "make setup"
    - "pip install ."
script:
    - "make test"
matrix:
    allow_failures:
        - python: "3.7-dev"
    include:
        - os: osx
          python: "3.6"
        - os: osx
          language: sh
          before_install: 
            - pyenv install 3.6.5
            - pyenv global 3.6.5
            - python3 -V
        - python: "3.7"
          env: LINTING=true
          script:
              - "make lint test"
